### ISSUE TITLE
Add get method

### ISSUE THREAD

**Issue by corysimmons** [posthumans/postcss-ant-grid#3]
**Update** See https://github.com/posthumans/postcss-ant-grid/issues/3#issuecomment-176825406

---

I'd really like to have a size getter.

I'm thinking the syntax could look something like this.

```css
.one-off {
  width: ant-get(1/3 auto 30px, 2);
  ant-gutter: 60px;
}
```

This would get the auto's `calc` formula (`index + 1` as it's a bit more readable to designer types).

The glaring caveat with this method is what if you wanted different gutters (or some other grid-related property) for sizes in the same element?

```css
.one-off {
  width: ant-get(1/3 auto 30px, 2);
  ant-gutter: 60px;
  height: ant-get(100px auto 15%, 2);
  ant-gutter: 120px;
  ant-grid: 1/2;
}
```

Both gets and `ant-grid` would be calculated with `ant-gutter: 120px;` right?

Ideally this syntax would work... If there are more than 1 `ant-` properties, whichever ones come after the `ant-get` or `ant-grid` within the ruleset are the ones used.

So this would work as expected:

```css
.one-off {
  width: ant-get(1/3 auto 30px, 2); /* calculated with 60px */
  ant-gutter: 60px;
  height: ant-get(100px auto 15%, 2); /* calculated with 120px */
  ant-gutter: 120px;
  ant-grid: 1/2; /* would be calculated with 120px since it appears last */
}
```

```css
.one-off {
  width: ant-get(1/3 auto 30px, 2);
  ant-gutter: 60px;
  height: ant-get(100px auto 15%, 2);
  ant-gutter: 120px;
  ant-grid: 1/2; /* would be calculated with 45px since it appears after ant-grid is defined */
  ant-gutter: 45px;
}
```

This would need to work with multiple `ant-` properties (like `ant-direction`, `ant-flexbox`, etc. etc. etc.) so the solution would have to be flexible.

The sooner we figure this one out, the better. I'd prefer to develop `ant-grid` with this as some sort of module we can use in `ant-grid` and `ant-get`.
